# Generated by Django 4.2.5 on 2023-09-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='0', upload_to='movie_image'),
            preserve_default=False,
        ),
    ]
